### ISSUE TITLE
Status of the project/ Is this project being pulled into official Lineage OS repo / page

### ISSUE THREAD

**Issue by ClundXIII** [a3y17lte/device-specific#1]
Hi,

(I am sorry for using an issue for this question, I couldn't find any forum.)

Is this going to be pulled into the official LineageOS device List anytime soon? What is the status of this project, is it stable to use or should I wait a few months until it is ready?

Simon

**Comment by ch8matt** [comment]
@ClundXIII Hey, you can check project on xda.
For moment it's not planned because I doesn't match all point on the lineage charter. Rom is pretty stable in my opinion, I use it as daily and can't notice a bug that make me want come on stock rom. 
I recommend you to try it to make yourself an opinion about it. 
Regards
Mcfy

**Comment by ch8matt** [comment]
@ClundXIII Xda link: https://forum.xda-developers.com/samsung-a-series-2017/development/rom-lineageos14-1-t3735022

**Comment by ClundXIII** [comment]
Thank you very much :)

**Comment by ch8matt** [comment]
@ClundXIII No problem,

**Comment by ch8matt** [comment]
Download link : host.mcfy.fr
- Be sure to download latest build -

**Comment by ClundXIII** [comment]
Will I be able to update the OS from the phone without flashing it again?
